#!/bin/sh

module=tuxedo-keyboard
version=3.1.4

set -e

case "$1" in
    remove)
        if [  "`dkms status -m $module`" ]
       	then
            dkms remove -m $module -v $version --all
            # Attempt to remove module, fail silently if module is already unloaded
            rmmod -s $module > /dev/null 2>&1 || true
        fi
        rm -f /etc/modprobe.d/tuxedo_keyboard.conf || true
    ;;

    upgrade|deconfigure)
        if [  "`dkms status -m $module`" ]
       	then
            dkms remove -m $module -v $version --all
            # Attempt to remove module, fail silently if module is already unloaded
            rmmod -s $module > /dev/null 2>&1 || true
        fi
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0

#DEBHELPER#

